// src/routeTree.gen.ts
// This file is auto-generated by TanStack Router on first `npm run dev`.
// Do not edit manually. Re-run dev server to regenerate.

/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck

export const routeTree = {};
